/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorClase;
import Modelo.Clase;
import Modelo.ServicioClase;
import javax.swing.JOptionPane;

/**
 *
 * @author pxand
 */
public class Clases extends javax.swing.JInternalFrame implements IVista<Clase> {
    ControladorClase ctrlClase;
    /**
     * Creates new form Clases
     */
    public Clases(ServicioClase servicioClase) {
        initComponents();
        this.ctrlClase = new ControladorClase(servicioClase,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        Tipotxt = new javax.swing.JTextField();
        Capacidadtxt = new javax.swing.JTextField();
        IDentrenadortxt = new javax.swing.JTextField();
        AnadirBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        BuscarBtn = new javax.swing.JButton();
        Horariotxt = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Clases");

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Horario");

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Capacidad");

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID Entrenador");

        IDtxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        IDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });

        Tipotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Tipotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tipotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipotxtActionPerformed(evt);
            }
        });

        Capacidadtxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Capacidadtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Capacidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadtxtActionPerformed(evt);
            }
        });

        IDentrenadortxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        IDentrenadortxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDentrenadortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDentrenadortxtActionPerformed(evt);
            }
        });

        AnadirBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        AnadirBtn.setText("Anadir");
        AnadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirBtnActionPerformed(evt);
            }
        });

        ModificarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        BuscarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        Horariotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Horariotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Horariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariotxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Horariotxt)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(IDentrenadortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tipotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Capacidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDentrenadortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Capacidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxtActionPerformed

    private void TipotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipotxtActionPerformed

    private void CapacidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadtxtActionPerformed

    private void IDentrenadortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDentrenadortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDentrenadortxtActionPerformed

    private void AnadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirBtnActionPerformed
        try {
            int id = Integer.valueOf(IDtxt.getText().trim());
            String tipo = Tipotxt.getText().trim();
            String horario = Horariotxt.getText().trim();
            String capacidadStr = Capacidadtxt.getText().trim();
            int capacidad = Integer.parseInt(capacidadStr);
            int idEntrenador = Integer.parseInt(IDentrenadortxt.getText().trim());
            if (IDtxt.getText().isBlank()||tipo.isBlank()|| horario.isBlank()||capacidadStr.isBlank()||IDentrenadortxt.getText().isBlank()) {
                return;
            }
            ctrlClase.registrar(id, tipo, horario, capacidad, idEntrenador);
            limpiar();
        } catch (NumberFormatException e) {
            this.mostrarError("Capacidad debe ser un número entero válido");
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_AnadirBtnActionPerformed

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        try {
            String idStr = IDtxt.getText().trim();
            if (idStr.isBlank()) {
                mostrarError("Debe buscar una clase primero");
                return;
            }
            int id = Integer.parseInt(idStr);

            String tipo = Tipotxt.getText().trim().isEmpty() ? null : Tipotxt.getText().trim();
            String horario = Horariotxt.getText().trim().isEmpty() ? null : Horariotxt.getText().trim();
            Integer capacidad = Capacidadtxt.getText().trim().isEmpty() ? null : Integer.parseInt(Capacidadtxt.getText().trim());
            int idEntrenador = Integer.parseInt(IDentrenadortxt.getText().trim());

            ctrlClase.actualizar(id, tipo, horario, capacidad, idEntrenador);
        } catch (NumberFormatException e) {
            this.mostrarError("Capacidad o ID inválido");
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        try {
            String idStr = IDtxt.getText().trim();
            if (idStr.isBlank()) {
                mostrarError("Ingresa el ID para eliminar");
                return;
            }
            int id = Integer.parseInt(idStr);
            ctrlClase.eliminar(id);
            limpiar();
        } catch (NumberFormatException e) {
            this.mostrarError("ID debe ser un número entero");
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        BusquedaClases dialog = new BusquedaClases(null, true);
        try {
            dialog.setControlador(ctrlClase);
        } catch (Exception ex) {
            System.getLogger(Clases.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        dialog.setVisible(true);

        Clase seleccionada = dialog.getClaseSeleccionada();
        if (seleccionada != null) {
            mostrarDatos(seleccionada);
        }
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void HorariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorariotxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirBtn;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField Capacidadtxt;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JTextField Horariotxt;
    private javax.swing.JTextField IDentrenadortxt;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JTextField Tipotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        IDtxt.setText("");
        Tipotxt.setText("");
        Horariotxt.setText("");
        Capacidadtxt.setText("");
        IDentrenadortxt.setText("");
    }

    @Override
    public void cambiarEstadoCampos(boolean estado) {
        Tipotxt.setEnabled(estado);
        Horariotxt.setEnabled(estado);
        Capacidadtxt.setEnabled(estado);
        IDentrenadortxt.setEnabled(estado);
    }

    @Override
    public void habilitarCampos() {
        IVista.super.habilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void deshabilitarCampos() {
        IVista.super.deshabilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public boolean confirmar(String msg, String titulo) {
        return JOptionPane.showConfirmDialog(this, msg, titulo,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        JOptionPane.showMessageDialog(this, msg, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public String solicitar(String msg, String titulo) {
        return JOptionPane.showInputDialog(this, msg, titulo, JOptionPane.QUESTION_MESSAGE);
    }

    
    @Override
    public void mostrarDatos(Clase entidad) {
        IDtxt.setText(String.valueOf(entidad.getId()));
        Tipotxt.setText(entidad.getTipo());
        Horariotxt.setText(entidad.getHorario());
        Capacidadtxt.setText(String.valueOf(entidad.getCapacidadMaxima()));
        IDentrenadortxt.setText(String.valueOf(entidad.getIdEntrenador()));
    }
}
