/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCliente;
import Modelo.Cliente;
import Modelo.ServicioCliente;
import Modelo.TiposMembresia;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author pxand
 */
public class Clientes extends javax.swing.JInternalFrame implements IVista<Cliente> {
    ControladorCliente ctrlCliente;
    /**
     * Creates new form 
     */
    public Clientes(ServicioCliente servicioCliente) {
        initComponents();
        this.ctrlCliente = new ControladorCliente(servicioCliente,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnadirBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        BuscarBtn = new javax.swing.JButton();
        Cedulatxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Nombretxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Contactotxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboMembresia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Nacimientotxt = new javax.swing.JTextField();
        Vencimientotxt = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Clientes");

        AnadirBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        AnadirBtn.setText("Anadir");
        AnadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirBtnActionPerformed(evt);
            }
        });

        ModificarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        BuscarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        Cedulatxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Cedulatxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cedulatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulatxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cedula");

        Nombretxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Nombretxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha Nacimiento");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Membresia");

        Contactotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Contactotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Contactotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactotxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contacto");

        ComboMembresia.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        ComboMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica", "Premium" }));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha Vencimiento");

        Nacimientotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Nacimientotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nacimientotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacimientotxtActionPerformed(evt);
            }
        });

        Vencimientotxt.setEditable(false);
        Vencimientotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Vencimientotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vencimientotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VencimientotxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contactotxt)
                    .addComponent(Cedulatxt)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nombretxt)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboMembresia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nacimientotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vencimientotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cedulatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nacimientotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contactotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Vencimientotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboMembresia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirBtnActionPerformed
       try {
            String cedula = Cedulatxt.getText().trim();
            String nombre = Nombretxt.getText().trim();
            String contacto = Contactotxt.getText().trim();
            String fechaNacStr = Nacimientotxt.getText().trim();
            String fechaVenStr = Vencimientotxt.getText().trim();
            TiposMembresia tipo = TiposMembresia.valueOf(ComboMembresia.getSelectedItem().toString().toUpperCase());

            LocalDate fechaNacimiento = LocalDate.parse(fechaNacStr, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            LocalDate fechaVencimiento = LocalDate.now();

            ctrlCliente.registrar(cedula, fechaNacimiento, fechaVencimiento, nombre, contacto, tipo);
            limpiar();
        } catch (DateTimeParseException e) {
            this.mostrarError("Formato de fecha inválido. Usa yyyy-MM-dd");
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
       limpiar();
    }//GEN-LAST:event_AnadirBtnActionPerformed

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        try {
            String cedula = Cedulatxt.getText().trim();
            if (cedula.isBlank()) {
                return;
            }

            String nombre = Nombretxt.getText().trim().isEmpty() ? null : Nombretxt.getText().trim();
            String contacto = Contactotxt.getText().trim().isEmpty() ? null : Contactotxt.getText().trim();
            LocalDate fechaNac = Nacimientotxt.getText().trim().isEmpty() ? null : 
                    LocalDate.parse(Nacimientotxt.getText().trim(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            LocalDate fechaVen = LocalDate.now();
            TiposMembresia tipo = ComboMembresia.getSelectedIndex() == 0 ? null : 
                    TiposMembresia.valueOf(ComboMembresia.getSelectedItem().toString().toUpperCase());

            ctrlCliente.actualizar(cedula, fechaNac, fechaVen, nombre, contacto, tipo);
            this.mostrarMensaje("Cliente modificado correctamente", "Éxito");
        } catch (DateTimeParseException e) {
            this.mostrarError("Formato de fecha inválido. Usa yyyy-MM-dd");
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        try {
            String cedula = Cedulatxt.getText().trim();
            if (cedula.isBlank()) {
                this.mostrarError("Ingresa la cédula del cliente a eliminar");
                return;
            }

            ctrlCliente.eliminar(cedula);
            this.mostrarMensaje("Cliente eliminado correctamente", "Éxito");
            limpiar();
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }
        limpiar();
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        BusquedaCliente dialog = new BusquedaCliente(null, true);
        try {
            dialog.setControlador(ctrlCliente);
        } catch (Exception ex) {
            System.getLogger(Clientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        dialog.setVisible(true);

        Cliente seleccionado = dialog.getClienteSeleccionado();
        if (seleccionado != null) {
            mostrarDatos(seleccionado);
        } 
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed

    private void CedulatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulatxtActionPerformed

    private void ContactotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactotxtActionPerformed

    private void NacimientotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacimientotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacimientotxtActionPerformed

    private void VencimientotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VencimientotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VencimientotxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirBtn;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField Cedulatxt;
    private javax.swing.JComboBox<String> ComboMembresia;
    private javax.swing.JTextField Contactotxt;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JTextField Vencimientotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        Cedulatxt.setText("");
        Nombretxt.setText("");
        Contactotxt.setText("");
        Nacimientotxt.setText("");
        Vencimientotxt.setText("");
        ComboMembresia.setSelectedIndex(0);
    }

    @Override
    public void cambiarEstadoCampos(boolean estado) {
        Cedulatxt.setEnabled(estado);
        Nombretxt.setEnabled(estado);
        Contactotxt.setEnabled(estado);
        Nacimientotxt.setEnabled(estado);
        Vencimientotxt.setEnabled(estado);
        ComboMembresia.setEnabled(estado);
    }

    @Override
    public void habilitarCampos() {
        IVista.super.habilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void deshabilitarCampos() {
        IVista.super.deshabilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }


    @Override
    public boolean confirmar(String msg, String titulo) {
        return JOptionPane.showConfirmDialog(this, msg, titulo, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        JOptionPane.showMessageDialog(this, msg, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public String solicitar(String msg, String titulo) {
        return JOptionPane.showInputDialog(this, msg, titulo, JOptionPane.QUESTION_MESSAGE);
    }

    @Override
    public void mostrarDatos(Cliente entidad) {
        Cedulatxt.setText(entidad.getCedula());
        Nombretxt.setText(entidad.getNombre());
        Contactotxt.setText(entidad.getContactos());
        Nacimientotxt.setText(String.valueOf(entidad.getFechaNacimientos()));
        Vencimientotxt.setText(String.valueOf(entidad.getFechaVencimiento()));
        ComboMembresia.setSelectedIndex(0);
    }
    
}
