/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorEntrenador;
import Modelo.Entrenador;
import Modelo.ServicioEntrenador;
import javax.swing.JOptionPane;

/**
 *
 * @author pxand
 */
public class EntrenadorVista extends javax.swing.JInternalFrame implements IVista<Entrenador> {
    private ControladorEntrenador controlador;
    /**
     * Creates new form Entrenador
     */
    
    
    public EntrenadorVista() {
        initComponents();
    }

    public EntrenadorVista(ServicioEntrenador servicio) {
        this();
        controlador = new ControladorEntrenador(servicio,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        Contactotxt = new javax.swing.JTextField();
        Nombretxt = new javax.swing.JTextField();
        Especialidadtxt = new javax.swing.JTextField();
        AnadirBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        BuscarBtn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Entrenador");

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contacto");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Especialidad");

        IDtxt.setEditable(false);
        IDtxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        IDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });

        Contactotxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Contactotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Contactotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactotxtActionPerformed(evt);
            }
        });

        Nombretxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Nombretxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });

        Especialidadtxt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Especialidadtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Especialidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadtxtActionPerformed(evt);
            }
        });

        AnadirBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        AnadirBtn.setText("Anadir");
        AnadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirBtnActionPerformed(evt);
            }
        });

        ModificarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        BuscarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(IDtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contactotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Especialidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Nombretxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Contactotxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDtxt)
                    .addComponent(Especialidadtxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxtActionPerformed

    private void ContactotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactotxtActionPerformed

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed

    private void EspecialidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadtxtActionPerformed

    private void AnadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirBtnActionPerformed
        String nombre = Nombretxt.getText();
        String contacto = Contactotxt.getText();
        String especialidad = Especialidadtxt.getText();
        try {
            controlador.registrar(nombre, contacto, especialidad);
        } catch (Exception e) {
            this.mostrarError("Error al añadir: " + e.getMessage());
        }
    }//GEN-LAST:event_AnadirBtnActionPerformed

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        String idStr = IDtxt.getText();
        if (idStr.isEmpty()) {
            mostrarError("Ingrese el ID para modificar");
            return;
        }
        int id = Integer.parseInt(idStr);
        String nuevoNombre = Nombretxt.getText();
        String nuevoContacto = Contactotxt.getText();
        String nuevaEspecialidad = Especialidadtxt.getText();
        try {
            controlador.actualizar(id, nuevoNombre, nuevoContacto, nuevaEspecialidad);
        } catch (Exception e) {
            this.mostrarError("Error al modificar: " + e.getMessage());
        }
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        String idStr = IDtxt.getText();
        if (idStr.isEmpty()) {
            this.mostrarError("Ingrese el ID para eliminar");
            return;
        }
        int id = Integer.parseInt(idStr);
        try {
            if (confirmar("¿Eliminar entrenador ID " + id + "?", "Confirmar")) {
                boolean eliminado = controlador.eliminar(id);
                if (eliminado) {
                    limpiar();
                }
            }
        } catch (Exception e) {
            this.mostrarError("Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        BusquedaEntrenador dialog = new BusquedaEntrenador(null, true);
        try {
            dialog.setControlador(controlador);
        } catch (Exception ex) {
            System.getLogger(EntrenadorVista.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        dialog.setVisible(true);

        Entrenador seleccionado = dialog.getEntrenadorSeleccionado();
        if (seleccionado != null) {
            mostrarDatos(seleccionado);
        }
    }//GEN-LAST:event_BuscarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirBtn;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField Contactotxt;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JTextField Especialidadtxt;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        IDtxt.setText("");
        Contactotxt.setText("");
        Nombretxt.setText("");
        Especialidadtxt.setText("");
    }

    @Override
    public void cambiarEstadoCampos(boolean estado) {
        IDtxt.setEnabled(estado);
        Contactotxt.setEnabled(estado);
        Nombretxt.setEnabled(estado);
        Especialidadtxt.setEnabled(estado);
    }


    @Override
    public boolean confirmar(String msg, String titulo) {
        return JOptionPane.showConfirmDialog(this, msg, titulo, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        JOptionPane.showMessageDialog(this, msg, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public String solicitar(String msg, String titulo) {
        return JOptionPane.showInputDialog(this, msg, titulo, JOptionPane.QUESTION_MESSAGE);
    }

    @Override
    public void mostrarDatos(Entrenador entrenador) {
        IDtxt.setText(String.valueOf(entrenador.getId()));
        Nombretxt.setText(entrenador.getNombre());
        Contactotxt.setText(entrenador.getContacto());
        Especialidadtxt.setText(entrenador.getEspecialidad());
    }
}
