/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorUsuario;
import Modelo.Roles;
import Modelo.ServicioUsuario;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author pxand
 */
public class Usuarios extends javax.swing.JInternalFrame implements IVista<Usuario> {
    ControladorUsuario ctrlUsuario;
    /**
     * Creates new form Usuarios
     */
    public Usuarios(ServicioUsuario servicioUsuario) {
        initComponents();
        this.ctrlUsuario = new ControladorUsuario(servicioUsuario,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        Usuariotxt = new javax.swing.JTextField();
        Contrasenatxt = new javax.swing.JTextField();
        AnadirBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        BuscarBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();
        RolesCombo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 153, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Usuarios");
        setMinimumSize(new java.awt.Dimension(628, 194));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contrasena");

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rol");

        IDtxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Usuariotxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        Contrasenatxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Contrasenatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenatxtActionPerformed(evt);
            }
        });

        AnadirBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        AnadirBtn.setText("Anadir");
        AnadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirBtnActionPerformed(evt);
            }
        });

        EliminarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        BuscarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        ModificarBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtnActionPerformed(evt);
            }
        });

        RolesCombo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RolesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Entrenador" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Usuariotxt)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AnadirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ModificarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contrasenatxt)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RolesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RolesCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Contrasenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnadirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirBtnActionPerformed
        try {
            int id = Integer.valueOf(IDtxt.getText().trim());
            String usuario = Usuariotxt.getText().trim();
            String contraseña = new String(Contrasenatxt.getText()).trim();
            Roles rol =  Roles.valueOf(RolesCombo.getSelectedItem().toString().toUpperCase());

            if (usuario.isEmpty() || contraseña.isEmpty()) {
                this.mostrarError("Usuario y contraseña son obligatorios");
                return;
            }

            ctrlUsuario.registrar(id, usuario, contraseña, rol);
            limpiar();
        } catch (Exception ex) {
            this.mostrarError(ex.getMessage());
        }
    }//GEN-LAST:event_AnadirBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        try {
            String textoId = IDtxt.getText().trim();
            if (textoId.isEmpty()) {
                this.mostrarError("Ingrese el ID a eliminar");
                return;
            }
            int id = Integer.parseInt(textoId);

            if (this.confirmar("¿Seguro que desea eliminar este usuario?", "Confirmar eliminación")) {
                ctrlUsuario.eliminar(id);
                this.mostrarMensaje("Usuario eliminado", "Éxito");
                limpiar();
            }
        } catch (NumberFormatException ex) {
            this.mostrarError("ID debe ser numérico");
        } catch (Exception ex) {
            this.mostrarError(ex.getMessage());
        }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        BusquedaUsuarios dialog = new BusquedaUsuarios(null, true);
        try {
            dialog.setControlador(ctrlUsuario);
        } catch (Exception ex) {
            System.getLogger(Usuarios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        dialog.setVisible(true);

        Usuario seleccionado = dialog.getUsuarioSeleccionado();
        if (seleccionado != null) {
            mostrarDatos(seleccionado);
        }
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
        try {
            String textoId = IDtxt.getText().trim();
            if (textoId.isEmpty()) {
                this.mostrarError("Primero busque un usuario para modificar");
                return;
            }
            int id = Integer.parseInt(textoId);

            String nuevoUsuario = Usuariotxt.getText().trim();
            if (nuevoUsuario.isEmpty()) nuevoUsuario = null;

            String nuevaContra = new String(Contrasenatxt.getText()).trim();
            if (nuevaContra.isEmpty()) nuevaContra = null;

            Roles nuevorol =  Roles.valueOf(RolesCombo.getSelectedItem().toString().toUpperCase());

            ctrlUsuario.actualizar(id, nuevoUsuario, nuevaContra, nuevorol);
            limpiar();
        } catch (NumberFormatException ex) {
            this.mostrarError("ID inválido");
        } catch (Exception ex) {
            this.mostrarError(ex.getMessage());
        }
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void ContrasenatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenatxtActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_ContrasenatxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirBtn;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField Contrasenatxt;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JComboBox<String> RolesCombo;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        IDtxt.setText("");
        Usuariotxt.setText("");
        Contrasenatxt.setText("");
        RolesCombo.setSelectedIndex(0);
    }

    @Override
    public void cambiarEstadoCampos(boolean estado) {
        Usuariotxt.setEnabled(estado);
        Contrasenatxt.setEnabled(estado);
        RolesCombo.setEnabled(estado);
    }

    @Override
    public void habilitarCampos() {
        IVista.super.habilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void deshabilitarCampos() {
        IVista.super.deshabilitarCampos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void mostrarDatos(Usuario usuario) {
        if (usuario instanceof Modelo.Usuario u) {
            IDtxt.setText(String.valueOf(u.getId()));
            Usuariotxt.setText(u.getNombreUsuario());
            Contrasenatxt.setText(""); 
            RolesCombo.setSelectedItem(u.getRol());
        }
    }

    @Override
    public boolean confirmar(String msg, String titulo) {
        return JOptionPane.showConfirmDialog(this, msg, titulo,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        JOptionPane.showMessageDialog(this, msg, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public String solicitar(String msg, String titulo) {
        return JOptionPane.showInputDialog(this, msg, titulo, JOptionPane.QUESTION_MESSAGE);
    }
}
